CREATE DATABASE API_RESTAURANTE;

-- CREATE SCHEMA PUBLIC AUTHORIZATION POSTGRES;

-- public."cliente" definition

-- Drop table

-- DROP TABLE public."cliente";

CREATE TABLE PUBLIC."cliente" (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255),
    CPF VARCHAR(11) UNIQUE,
    TELEFONE VARCHAR(20),
    DATANASCIMENTO TIMESTAMP,
    ENDERECO VARCHAR(255)
    -- CONSTRAINT CLIENTE_PKEY PRIMARY KEY (ID)
    );

CREATE TABLE PUBLIC."controleestoque" (
    ID SERIAL PRIMARY KEY,
    ITEMESTOQUE VARCHAR(255),
    QUANTIDADEITEM INTEGER,
    VALORUNIDADE DOUBLE PRECISION
    -- CONSTRAINT CONTROLEESTOQUE_PKEY PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC."fechamentopedido" (
    ID SERIAL PRIMARY KEY,
    NUMEROPEDIDO INT8,
    IDCLIENTE INT8,
    ITEMPEDIDO VARCHAR(255),
    QUANTIDADEITEM INTEGER,
    VALORUNIDADE DOUBLE PRECISION
    -- CONSTRAINT FECHAMENTOLANCAMENTOPEDIDO_PKEY PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC."fornecedor" (
    ID SERIAL PRIMARY KEY,
    NOMEFORNECEDOR VARCHAR(255),
    CNPJ VARCHAR(14),
    ITEMPEDIDO INTEGER,
    QUANTIDADEITEM INTEGER,
    VALORUNIDADE DOUBLE PRECISION
    -- CONSTRAINT FORNECEDOR_PKEY PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC."funcionario" (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255),
    CPF VARCHAR(11) UNIQUE,
    TELEFONE VARCHAR(20),
    DATANASCIMENTO TIMESTAMP,
    ENDERECO VARCHAR(255)
    -- CONSTRAINT FUNCIONARIO_PKEY PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC."lancamentopedido" (
    ID SERIAL PRIMARY KEY,
    NUMEROPEDIDO INT8,
    IDCLIENTE INT8,
    ITEMPEDIDO VARCHAR(255),
    QUANTIDADEITEM INTEGER,
    VALORUNIDADE DOUBLE PRECISION
    -- CONSTRAINT LANCAMENTOPEDIDO_PKEY PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC."produto" (
    ID SERIAL PRIMARY KEY,
    NOMEPRODUTO VARCHAR(255),
    TIPOPRODUTO VARCHAR(255),
    DESCRICAO VARCHAR(255),
    VALORUNIDADE DOUBLE PRECISION,
     DATACOMPRA TIMESTAMP
    -- CONSTRAINT PRODUTO_PKEY PRIMARY KEY (ID)
);