CREATE TABLE API_RESTAURANTE IF NOT EXISTS;

CREATE SCHEMA PUBLIC AUTHORIZATION POSTGRES;

-- public."cliente" definition

-- Drop table

-- DROP TABLE public."cliente";

CREATE TABLE PUBLIC."cliente" (
    ID INT8 NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(15) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    DATANASCIMENTO TIMESTAMP,
    ENDERECO VARCHAR(255) NOT NULL,
    CONSTRAINT CLIENTE_PKEY PRIMARY KEY (ID)
);